### ISSUE TITLE
Can't redirect if url has an accent

### ISSUE THREAD

**Issue by DarthWound** [stevensona/briskforms#19]
Hello!

Thank you for this great service, nice to see something free and complete for us having small personal websites.

However it seems that if the url where people are redirected ("message sent" page for example) contains an accent then service crashes _(Application error - An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.)_.

Mine is "../envoyé.html" with an acute accent, "envoyé" means "sent". Before the page was "../thx.html" and everything worked, so it's why I assume accent is source of the issue here.

**Comment by stevensona** [comment]
Thank you for reporting the issue. It should be fixed now.

**Comment by DarthWound** [comment]
Thank you, that was fast.
I confirm, bug fixed :)
Have a nice day!
