### ISSUE TITLE
Ignore date input

### ISSUE THREAD

**Issue by zxdawn** [stevensona/briskforms#21]
The email doesn't have the selected date information:

Here's the example:
```
<form method="post" action="my_id">

<div class="form-group">
  <label for="date">Deadline (for student)</label>
  <input type="date" min="2019-01-01" max="2050-01-01" step="7" class="form-control">
</div>

<button type="submit">Send</button>
</form>
```

**Comment by stevensona** [comment]
Input fields must have a `name` attribute in order to be submitted as part of the form's POST request.

Add `name="date"` to the input element.
